server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: report
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**, 
        - id: mgmt
          uri: http://localhost:8083
          predicates:
            - Path=/mgmts/**, /reportDetails/**
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notificationHistories/**, /notificationLists/**
        - id: phone
          uri: http://localhost:8085
          predicates:
            - Path=/phones/**, /searchPhones/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/reports/**, 
        - id: mgmt
          uri: http://mgmt:8080
          predicates:
            - Path=/mgmts/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notificationHistories/**, 
        - id: phone
          uri: http://phone:8080
          predicates:
            - Path=/phones/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
